source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/alphatroya/ATRCocoapodsSpecs.git'

platform :ios, '9.0'

inhibit_all_warnings!
use_frameworks!

def standard_pods
    pod 'MobileEngageSDK', '~> 0.9.0'
    pod 'PromiseKit', '~> 6.2'
    pod 'AppsFlyerFramework', '~> 4.7.3'
    pod 'WebRTC', '57.5.16123'
    pod 'Starscream', '~> 3.0'
    pod 'Fabric', '~> 1.7'
    pod 'Crashlytics', '~> 3.9'
    pod 'DZNEmptyDataSet', '~> 1.8'
    pod 'Pulley', '~> 2.3'
    pod 'GoogleTagManager','~> 3.15.0'
    pod 'Google/Analytics', '~> 3.1'
    pod 'ATRLogFormatter', '~> 1.5'
    pod 'SnapKit', '~> 4.0'
    pod 'Alamofire', '~> 4.7'
    pod 'CodableAlamofire', '~> 1.1'
    pod 'RealmSwift', '~> 3.1.1'
    pod 'Mapbox-iOS-SDK', '3.7.3'
    pod 'Pushwoosh', '~> 5.4'
    pod 'libPhoneNumber-iOS', '~> 0.8'
    pod 'HockeySDK', '~> 5.0'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'MessageKit', '~> 0.13.5'
    pod 'LNNotificationsUI', :git => 'https://github.com/iosteam-sinodynamic/LNNotificationsUI'
    pod 'ReactiveCocoa', '~> 7.0'
    pod 'SocketRocket', '~> 0.5'
    pod 'ReachabilitySwift', '~> 4.1'
    pod 'KeychainAccess', '~> 3.1'
    pod 'GoogleIDFASupport', '~> 3.14'
    pod 'SDWebImage', '~>4.3'
    pod 'NYTPhotoViewer', '~> 1.2'
    pod 'SDVersion', '~>4.3'
    pod 'VK-ios-sdk', '~>1.4'
    pod 'APNGKit', '~> 1.0'
    pod 'FacebookCore'
end

target "doctor-on-call-client" do
    standard_pods
end

target 'DOCTests' do
    inherit! :search_paths
    standard_pods
    pod "Cuckoo"
end



post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
